flow2ml/Flow2ML

README.md

**Issue#20**
added contributors section in the readme file, it will show the profile of contributors of this project.

added contributors section in readme file

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general_issue.md
.github/PULL_REQUEST_TEMPLATE.md

[qa]:Add Issue & PR templates

---

README.md
requirements.txt

Added Requirements.txt

---

README.md
flow2ml/Data_Loader.py

- Correct tulpe spelling to tuple
- Fix classPath seperators to include both Linux and Windows
- Remove redundant channels from image if it contains more than the specified number of channels
Fixes #32

Fix Data_Loader.py

---

.github/config.yml

Added welcome bot

---

README.md

the repository status of issues,forks,stars,pr ,etc has been attached in readme.md file

Status Bar attached to readme.md file

---

.github/workflows/main.yml
.github/workflows/publish_pypi.yml
.github/workflows/python_linter.yml

Adds Github actions for:
1. Running syntax checks for .py files withevery pull request. 
2. Publishing the package to PyPi whenever a new release is published in Github (via pushing tagged commit.)
Fixes #31

Add Github workflow 

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py

Added a method in Data_Augumentation.py file for flipping the image based on technique and parameters given by the user. Flip: 1 flips it on y axis, 0 flips it on x axis and -1 flips it on both axis. The images are added to class/FlippedImages.
```
techniques = {'flip': 1}
flow.applyAugmentation( techniques )
```
Fixes #56 
Original, flip:'horizontal', flip:'vertical', flip:'cross'
</p>

Add Flip augmentation technique

---

tests/unit/Tests.py

Added some tests using `unittest` to check the various functionalities if they are working as expected:
- Mocks data for 5 classes with 5 images each
- Checks if the directories for image paths are correctly set
- Checks if the classes for images are correctly found
- Checks if the filters are applied and found in the corresponding folders
- Checks if the processedData folder created correctly contains all the filtered images
- Checks if the sizes of train and test are split correctly
- Checks if the images are resized according to the dimensions given
Currently, I have put all the tests in a single file since parts of the code are dependant on each other. Tests are separated into different methods. I have if tested the various outputs (images/variables) are produced as expected and used …

Automated unit tests for functionalities

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md
requirements.txt

Added a method in Data_Augumentation.py file for shearing the image based on technique and parameters given by the user. It takes the angle for shearing the image along each axis.
```
operations = {'shear': {'x_axis': 5, 'y_axis': 5}}
```
Fixes #58 
1. Original
2. 'shear': {'x_axis': 5, 'y_axis': 5}
3. 'shear': {'x_axis': -20, 'y_axis': -10}
</p>

Add shear augmentation technique

---

README.md
flow2ml/Filters.py
flow2ml/README.md

Added bilateral filter code to filters.py
Fixes #54 
I have taken two blurred images from geeksforgeeks and geekscoders for better visualisation of the results and a third one I've added from my own collection to show how bilateral filter evens the image out,if there are any other pictures you'd like to see it work on, I'll add more.
1)
Before filter:
After filter:
2)
Before filter:
After filter:
3)
Before filter:
After filter:

Added bilateral filter

---

README.md

I have added the license as suggested . Kindly check . Thank you.
Fixes # 68
- [ x] This change requires a documentation update
- [ x] I have made corresponding changes to the documentation.

#68 issue is resolved

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

Added a method in the Data_Augumentation.py file for cropping the image based on the parameters given by the user. 'crop': random gives random crops of the image, else it takes 4 coordinates for cropping the image.
```
operations = {'crop': [50, 100, 50, 100]}
```
As of now, I haven't added a feature to ask the user to review each and every image -  it would take a very long time with a large dataset, However, do let me know if I should make changes.
Fixes #59 
'crop': [50, 100, 50, 100]
</p>
'crop': 'random'
width = "50"/>
</p>

Add cropping augmentation technique

---

README.md
flow2ml.egg-info/SOURCES.txt
flow2ml/README.md
flow2ml/Tf_Results.py
flow2ml/__init__.py

A class for automated evaluation of tensorflow models that will accept the model's history as an input and make the roc curves, confusion matrix and pr curves. The class can have an additional method to create a doc file with those plots.
Fixes #75

automated analysis support for tensorflow models

---

flow2ml/Data_Augumentation.py
flow2ml/Data_Loader.py
flow2ml/Filters.py
flow2ml/Flow.py
setup.py

Improved code standards as per PEP8

---

README.md

Test dataloader, all filters and augmentation techniques to see if the operations work as expected with greyscale images. Used an image with only 1 channel and verified it by checking if it is in L mode with the PIL mode.
Fixes #41 
Original, Laplacian filter, sobelx filter, flipped, rotated
</p>

Test codebase with greyscale

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

Added the code for histogram Equalisation 

---

flow2ml/Data_Augumentation.py
flow2ml/Flow.py

deployed tensorflow models

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

Added a method in Data_Augumentation.py file for adding greyscale augmentation.
```
operations = {'greyscale': True}
```
Fixes #87 
Original, 'greyscale':True
</p>

Added greyscale augmentation

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

added code for CLAHE operation

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

Added the code for morphological transformations

---

flow2ml/Auto_Results.py
flow2ml/Data_Augumentation.py
flow2ml/Data_Loader.py
flow2ml/Filters.py
flow2ml/Flow.py
flow2ml/Tf_Results.py

Improves code quality by adding exception handling, documentation updates and OS management. 
Fixes #34

Improve code quality

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

#103 
- [x
] Any dependent changes have been merged and published in downstream modules.

Added code for Thresholding augmentation

---

.gitignore
README.md
requirements.txt
tests/unit/README.md
tests/unit/Tests.py

Added unit tests for filters and dataloader.

Added original unit tests

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

Added code for Changing Color Space

---

README.md
requirements.txt

Updated requirements and README with pandas and seaborn packages.
Fixes #121

Updated requirements

---

README.md
flow2ml/Data_Augumentation.py
flow2ml/Filters.py
flow2ml/Flow.py

Creates connection between filters.py and Augmentations.py in such a way that user should be able to apply filters on augmented images and vice versa
Fixes #92 
Running the following code to apply augmentations on filters
```
filters = ["median", "laplacian"]
flow.applyFilters( filters )
operations = {'flipped': 'horizontal', 'rotated': 90, 'apply_on_filters': ['laplacian']}
```
Rotatedlaplacianapple_2 and Rotatedlaplacianapple_3
</p>
Running the following code to apply filters on augmentations
```
operations = {'flipped': 'horizontal', 'rotated': 90}
filters = ["median", "laplacian", {'apply_on_augmentation': ['rotated']}]
flow.applyFilters( filters )
```
MedianRotatedorange_2 and …

Connect aug filters

---

README.md
flow2ml/Flow.py
flow2ml/README.md

added code for deployment of tensorflow

---

README.md
flow2ml/Auto_Results.py
flow2ml/Flow.py
flow2ml/Image_Quality.py
flow2ml/README.md
flow2ml/Tf_Results.py
requirements.txt

Added a class that calculates the BRISQUE score of each image in processedData
Fixes #91

Score images using BRISQUE

---

README.md
flow2ml/Filters.py
flow2ml/Flow.py
flow2ml/README.md

added code for canny edge detector

---

flow2ml/Flow.py

Fixed a small error in visualiseCountplot function for cases when class imbalance is present.

Fixed errors with visualiseCountplot

---

README.md
flow2ml/Flow.py

Fixes the following issues:
- corrects the README code for deployment of tensorflow models
- corrects the conditions for deployment in multiple formats
- saves models in the correct path instead of different locations
- adds exception handling

Fix bugs in model deployment

---

README.md
flow2ml/Flow.py
flow2ml/Image_Quality.py
flow2ml/README.md

Added an option to calculate image quality score using entropy
```
image_quality = "entropy"
flow.calculateImageQuality( image_quality )
```

Add entropy scores

---

flow2ml/Flow.py
flow2ml/README.md

Added a method to check and detect blur in all images provided by the user to check if the focus measure if below a certain threshold. The threshold used here is 100.
</p>

Detect blur using Laplacian filter

---

README.md
flow2ml/Auto_Results.py
flow2ml/Tf_Results.py

Fixes issues with the previous implementation where the path does not work for Windows users. Also handled the condition for creating results directory since it is already created when we initialise Flow.py.

Fix path errors in results

---

examples/README.md

Fix the sample code README by incorporating changes suggested to reorder the code.

Reorder code

---

examples/README.md
flow2ml/Process_Csv.py
flow2ml/README.md
flow2ml/__init__.py

Initialises a class for basic exploratory steps with non image files (csv).
```
from flow2ml import Process_Csv
df = pd.read_csv('./Tips.csv')
x = Process_Csv(df)
```

Making code compatible enough for non-image datasets

---

examples/README.md
flow2ml/Data_Augumentation.py
flow2ml/Flow.py
flow2ml/README.md

Added a method in Data_Augumentation.py file enhancing brightness using log transform.
```
operations = {'brightnessenhanced':True}
```
Fixes #88 
Original, enhanced
</p>

add log transform

---

examples/README.md
flow2ml/Process_Csv.py
flow2ml/README.md

Adds basic visualization steps with non image files (csv).
```
df = pd.read_csv('./Tips.csv')
x = Process_Csv(df)
x.create_analysis_docx()
x.create_visualisation_docx()
```

visualise csv

---

flow2ml/Data_Loader.py
flow2ml/Flow.py

fix get dataset issues

---

flow2ml/Data_Loader.py
flow2ml/Flow.py

Revert changes again
